server:
  port: 8080

spring:
  soap:
    ws:
      uri: http://localhost:8080/ws
      default-uri: http://localhost:8080/ws
      timeout:
        connect: 5000
        read: 5000

logging:
  level:
    org.springframework: INFO
    com.example.bank: DEBUG

# Database configuration (example)
# Uncomment and configure if using a database
# spring:
#   datasource:
#     url: jdbc:mysql://localhost:3306/bankdb
#     username: your_username
#     password: your_password
#     driver-class-name: com.mysql.cj.jdbc.Driver

# Uncomment if using JPA
# spring:
#   jpa:
#     hibernate:
#       ddl-auto: update
#     show-sql: true

# SOAP service configuration
soap:
  service:
    name: BankService
    namespace: http://example.com/bank
    endpoint: /bank
